<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'ValeCheck Report' }}</title>
    <style>
        /* dompdf renders plain CSS2.1/partial CSS3 — no Tailwind utilities
           are available here, so this is hand-written, not compiled. */
        body { font-family: 'Helvetica', Arial, sans-serif; color: #10243A; font-size: 11px; margin: 0; padding: 0; }
        .header { border-bottom: 3px solid #E31B23; padding-bottom: 10px; margin-bottom: 16px; }
        .logo { font-size: 18px; font-weight: bold; }
        .logo .navy { color: #10243A; }
        .logo .red { color: #E31B23; }
        .tag { font-size: 9px; text-transform: uppercase; letter-spacing: 1px; color: #E31B23; font-weight: bold; }
        h1 { font-size: 18px; margin: 10px 0 2px; }
        .reg { font-family: 'Courier New', monospace; color: #666; margin: 0 0 14px; }
        .section { border: 1px solid #DDD; border-radius: 4px; padding: 10px 12px; margin-bottom: 10px; }
        .section-title { font-size: 9px; text-transform: uppercase; letter-spacing: 1px; color: #888; font-weight: bold; margin-bottom: 6px; }
        .grid { width: 100%; border-collapse: collapse; }
        .grid td { vertical-align: top; padding: 4px; }
        .headline { background: #10243A; color: #fff; padding: 14px; border-radius: 4px; margin-bottom: 14px; }
        .headline .label { font-size: 9px; text-transform: uppercase; color: #AAB4C0; }
        .headline .value { font-size: 20px; font-weight: bold; }
        .warn { color: #E31B23; font-weight: bold; }
        .ok { color: #10243A; }
        table.data { width: 100%; border-collapse: collapse; font-size: 10px; }
        table.data th { text-align: left; color: #888; font-weight: normal; border-bottom: 1px solid #DDD; padding: 3px 4px; }
        table.data td { padding: 3px 4px; border-bottom: 1px solid #F0F0F0; }
        ul { margin: 4px 0; padding-left: 16px; }
        .disclaimer { font-size: 8px; color: #999; margin-top: 16px; line-height: 1.5; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; font-size: 8px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo"><span class="navy">VALE</span><span class="red">CHECK</span></div>
        <div class="tag">{{ $tag ?? '' }}</div>
    </div>

    @yield('content')

    <div class="disclaimer">
        Generated by ValeCheck on {{ now()->format('d M Y, H:i') }} for {{ $check->registration }}. This document is a
        point-in-time summary of the on-screen report and does not update after generation.
    </div>
</body>
</html>
